pipeline:
  compile and tests:
    image: edouardlopez/docker-criterion:latest
    commands:
      - mkdir -p build
      - gcc -I include -o build/out testcase/test.c src/*.c -lcriterion
      - build/out --pattern execise/* --tap

# matrix:
#   TESTRANGE: [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30 ]

guide:
  name: C test
  desc: >
    Example project to demonstrate unit testing C
    code
  labels:
    - C
